const data = [
  {
    title: "Margherita Pizza",
    description: "Classic Margherita with fresh mozzarella and basil.",
    price: 12.99,
    imageURL: "https://example.com/images/margherita.jpg",
    foodTags: "pizza,vegetarian",
    category: "Italian",
    code: "MP001",
    isAvailable: true,
    resturant: "60b8d295c45e3a44d8f8a5c1",
    rating: 4.8,
    ratingCount: 152,
  },
  {
    title: "Sushi Platter",
    description: "Assorted sushi platter with fresh fish.",
    price: 24.99,
    imageURL: "https://example.com/images/sushi.jpg",
    foodTags: "sushi,seafood",
    category: "Japanese",
    code: "SP002",
    isAvailable: true,
    resturant: "60b8d295c45e3a44d8f8a5c2",
    rating: 4.5,
    ratingCount: 98,
  },
  {
    title: "Chicken Tikka Masala",
    description: "Grilled chicken pieces in a spicy tomato curry.",
    price: 15.49,
    imageURL: "https://example.com/images/tikka.jpg",
    foodTags: "chicken,spicy",
    category: "Indian",
    code: "CTM003",
    isAvailable: true,
    resturant: "60b8d295c45e3a44d8f8a5c3",
    rating: 4.7,
    ratingCount: 203,
  },
  {
    title: "Caesar Salad",
    description: "Crisp romaine lettuce with Caesar dressing.",
    price: 9.99,
    imageURL: "https://example.com/images/caesar.jpg",
    foodTags: "salad,vegetarian",
    category: "American",
    code: "CS004",
    isAvailable: true,
    resturant: "60b8d295c45e3a44d8f8a5c4",
    rating: 4.3,
    ratingCount: 67,
  },
  {
    title: "Pad Thai",
    description: "Stir-fried rice noodles with shrimp, eggs, and peanuts.",
    price: 13.99,
    imageURL: "https://example.com/images/padthai.jpg",
    foodTags: "noodles,seafood",
    category: "Thai",
    code: "PT005",
    isAvailable: true,
    resturant: "60b8d295c45e3a44d8f8a5c5",
    rating: 4.6,
    ratingCount: 120,
  },
];
